import os
import threading


class Constant():
    TORCH_HOME = "./torch_cache"  # 预训练模型保存路径
    GEFFNET_LIST = ['efficientnet_b0',
                    'efficientnet_b1',
                    'efficientnet_b2',
                    'efficientnet_b3',
                    'efficientnet_b4',
                    'efficientnet_b5',
                    'efficientnet_b6',
                    'efficientnet_b7',
                    'efficientnet_b8',
                    'efficientnet_l2',
                    'efficientnet_es',
                    'efficientnet_em',
                    'efficientnet_el',
                    'efficientnet_cc_b0_4e',
                    'efficientnet_cc_b0_8e',
                    'efficientnet_cc_b1_8e',
                    'efficientnet_lite0',
                    'efficientnet_lite1',
                    'efficientnet_lite2',
                    'efficientnet_lite3',
                    'efficientnet_lite4',
                    'tf_efficientnet_b0',
                    'tf_efficientnet_b1',
                    'tf_efficientnet_b2',
                    'tf_efficientnet_b3',
                    'tf_efficientnet_b4',
                    'tf_efficientnet_b5',
                    'tf_efficientnet_b6',
                    'tf_efficientnet_b7',
                    'tf_efficientnet_b8',
                    'tf_efficientnet_b0_ap',
                    'tf_efficientnet_b1_ap',
                    'tf_efficientnet_b2_ap',
                    'tf_efficientnet_b3_ap',
                    'tf_efficientnet_b4_ap',
                    'tf_efficientnet_b5_ap',
                    'tf_efficientnet_b6_ap',
                    'tf_efficientnet_b7_ap',
                    'tf_efficientnet_b8_ap',
                    'tf_efficientnet_b0_ns',
                    'tf_efficientnet_b1_ns',
                    'tf_efficientnet_b2_ns',
                    'tf_efficientnet_b3_ns',
                    'tf_efficientnet_b4_ns',
                    'tf_efficientnet_b5_ns',
                    'tf_efficientnet_b6_ns',
                    'tf_efficientnet_b7_ns',
                    'tf_efficientnet_l2_ns',
                    'tf_efficientnet_l2_ns_475',
                    'tf_efficientnet_es',
                    'tf_efficientnet_em',
                    'tf_efficientnet_el',
                    'tf_efficientnet_cc_b0_4e',
                    'tf_efficientnet_cc_b0_8e',
                    'tf_efficientnet_cc_b1_8e',
                    'tf_efficientnet_lite0',
                    'tf_efficientnet_lite1',
                    'tf_efficientnet_lite2',
                    'tf_efficientnet_lite3',
                    'tf_efficientnet_lite4']
